language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
 - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install --no-progress --prefer-source

script:
  - find inc src tests \( -name '*.php' \) -exec php -l {} \;
  - vendor/bin/phpunit

notifications:
  email: false
  slack:
    rooms: inpsyde:pb4VD0j0HYkb3lHmppSmmdxH
    on_start: never
    on_failure: always
    on_success: change
