name: PHP integration tests
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['php72', 'php73', 'php74']
        steps:
            -   uses: actions/checkout@v2

            -   name: Copy wait-for script
                uses: canastro/copy-file-action@master
                with:
                    source: "tests/docker/wait-for.sh"
                    target: "tests/docker/${{ matrix.php-versions }}/wait-for.sh"

            -   name: Run integration tests
                working-directory: ./tests/docker
                run: docker-compose run -T ${{ matrix.php-versions }} sh -c "wait-for.sh fasti-mysql:3306 -t 15 -- composer install -q -n -a --no-progress --prefer-dist && composer tests:integration"
